"""57fda18 の P5-a 基準を作る、S4b-1b の実装前の台本 (S4b1b v0.11 §6-4 Y6)。

実行 (プロジェクトの Python 3.12.10 / numpy 2.5.3 / scipy 1.18.1):
    .venv/Scripts/python.exe -B tools/s4b1b_golden.py tests/golden_s4b1b.json
実装後の照合 (既存ファイルを変更しない):
    .venv/Scripts/python.exe -B tools/s4b1b_golden.py --check tests/golden_s4b1b.json

1a の台本 (tools/s4b1a_golden.py、凍結) の場面と取り方をそのまま使い、model.5 を足す。
model.1〜4 の 18 場面は 1a の golden と同じ値になる (build_golden の中で確かめる)。

model.5 (learnable × Q、1a の格子の道) の 2 つの世界 × 4 入口:
  model5:      所要なし。学ぶ 2 行動の観測と、固定の行動の観測
  model5/hand: 所要あり (a は 1 秒か 5 秒)。進行中の a を observed = 1 秒の境界で
               持つ (所要の 2 つの枝と、測る時刻の 2 つの枝の平均を通る)
拒む場面 (plan_s4c・decide_s4c・lookahead) は例外の型と文面を残す。
"""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


sys.dont_write_bytecode = True
sys.path.insert(0, str(Path(__file__).resolve().parent))


from s4b1a_golden import NS, Scene, canonical, capture, model_scene, null_q_scene
from sui.model import model_json
from worlds import HandHistory, _lattice_model


MODES = ("plan_s4c", "decide_s4c", "one_step", "lookahead")


def model5_scene(hand):
    h = HandHistory(run="goldenlattice", wall=100)
    h.boot()
    if hand:
        model = _lattice_model(durations={"a": ((1., .5), (5., .5)), "b": ((0., 1.),), "f": ((0., 1.),)},
                               measures={a: "report" for a in ("a", "b", "f")})
        h.start("a")  # 進行中。observed = 1 秒なので 1 秒の枝も残る
        h.observe(h.start("a", 1), "x", 1)
        h.observe(h.start("f", 2), "y", 2)
    else:
        model = _lattice_model()
        h.observe(h.start("a", 1), "x", 1)
        h.observe(h.start("b", 2), "y", 2)
        h.observe(h.start("f", 3), "x", 3)
        h.observe(h.start("a", 4), "y", 4)
    h.at(4)
    assert json.loads(model_json(model))["scheme"] == "sui.model.5"
    return Scene(model, h, ("a", "b", "f"), 4 * NS, NS if hand else 4 * NS)


def build_golden():
    result = {}
    for version in range(1, 5):
        for mode in MODES:
            result[f"model{version}/{mode}"] = capture(model_scene(version), mode)
    for mode in ("one_step", "lookahead"):
        result[f"model3/null_q/{mode}"] = capture(null_q_scene(), mode, rare=True)
    # 1a の基準と同じ (同じ台本の同じ場面)。違えば 57fda18 で作っていない。
    baseline = json.loads((Path(__file__).resolve().parents[1] / "tests/golden_s4b1a.json")
                          .read_text(encoding="utf-8"))
    assert result == baseline, "model.1〜4 differ from tests/golden_s4b1a.json"
    for name, hand in (("model5", False), ("model5/hand", True)):
        for mode in MODES:
            result[f"{name}/{mode}"] = capture(model5_scene(hand), mode)
        assert result[f"{name}/plan_s4c"] == result[f"{name}/decide_s4c"]
        assert result[f"{name}/one_step"]["refused"] is None
    return result


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("path", type=Path, help="output path (or existing baseline with --check)")
    parser.add_argument("--check", action="store_true", help="compare bytes without writing")
    args = parser.parse_args()
    first = canonical(build_golden())
    second = canonical(build_golden())
    if first != second:
        raise AssertionError("golden generation is not deterministic")
    if args.check:
        if args.path.read_bytes() != first:
            raise SystemExit("P5-a mismatch: generated bytes differ from the baseline")
        print(f"P5-a matched: {args.path} ({len(first)} bytes)")
    else:
        args.path.write_bytes(first)
        print(f"Wrote {args.path}: {len(json.loads(first))} scenes, {len(first)} bytes, "
              f"sha256={hashlib.sha256(first).hexdigest()}")


if __name__ == "__main__":
    main()
